<a href="https://colab.research.google.com/github/Rohitha-M-Raghu/DEMO/blob/main/CLUSTERING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CLUSTERING PROGRAM IMPLEMENTED USING K-MEANS ALGORITHM
1. Random placing k centroids, one for each cluster
2. Calculate the distance of each point from each centroid
3. Assign each data point(object to its closest centroid, 
   creating cluster.
4. Recalculate the position of the k centroids
5. Repeat the steps 2-4, until the centroids no longer
   moves

In [1]:
from sklearn.cluster import KMeans
import numpy as np

x = np.array([[1, 2], [1, 4], [1, 0],[10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters = 2, random_state = 0).fit(x)

kmeans.labels_



array([1, 1, 1, 0, 0, 0], dtype=int32)

PREDICTION

In [2]:
kmeans.predict([[0, 0], [12, 3]])


array([1, 0], dtype=int32)

CLUSTERING CENTRES

In [3]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])